version: '3.8'

services:
  # Serviço da Aplicação (PHP)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: gestao-produtos-app
    container_name: gestao-produtos-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - db

  # Serviço do Banco de Dados (MySQL)
  db:
    image: mysql:8.0
    container_name: gestao-produtos-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD} # Use a mesma senha do seu .env
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306" # Expõe a porta para o seu PC, se quiser conectar com um cliente de DB

  # Serviço do Servidor Web (Nginx)
  nginx:
    image: nginx:alpine
    container_name: gestao-produtos-nginx
    restart: unless-stopped
    ports:
      - "8000:80" # Acesse a aplicação em http://localhost:8000
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

volumes:
  db-data:
    driver: local