version: '3.8'

# Bloco principal onde todos os serviços (contêineres) são definidos
services:

  # Serviço da Aplicação (PHP)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: gestao-produtos-app
    container_name: gestao-produtos-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks: # Adicionado para comunicação
      - gestao-produtos-net

  # Serviço do Banco de Dados (MySQL)
  db:
    image: mysql:8.0
    container_name: gestao-produtos-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks: # Adicionado para comunicação
      - gestao-produtos-net

  # Serviço do Servidor Web (Nginx)
  nginx:
    image: nginx:alpine
    container_name: gestao-produtos-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks: # Adicionado para comunicação
      - gestao-produtos-net

  # Serviço do phpMyAdmin (Adicionado e Corrigido)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: gestao-produtos-phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db # A chave para a conexão funcionar
    depends_on:
      - db
    networks: # Adicionado para comunicação
      - gestao-produtos-net

# Define a rede que permite a comunicação entre os contêineres
networks:
  gestao-produtos-net:
    driver: bridge

# Define o volume para persistir os dados do banco de dados
volumes:
  db-data:
    driver: local